// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTGWnMTIhw6LD6bJ2buDzifocFv9rX0gA',
    appId: '1:428336244677:web:4da69afbbf571be307cdac',
    messagingSenderId: '428336244677',
    projectId: 'shopify-1ac61',
    authDomain: 'shopify-1ac61.firebaseapp.com',
    storageBucket: 'shopify-1ac61.firebasestorage.app',
    measurementId: 'G-Z0QEL3PD0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsG3R4ZKrJ65w1RfcoeDh6AB5yBmhsRcE',
    appId: '1:428336244677:android:094c94373564824a07cdac',
    messagingSenderId: '428336244677',
    projectId: 'shopify-1ac61',
    storageBucket: 'shopify-1ac61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqAr8hM4PmOxqvquj3KRhlomQeqUwrx7A',
    appId: '1:428336244677:ios:42fadee00e7855f107cdac',
    messagingSenderId: '428336244677',
    projectId: 'shopify-1ac61',
    storageBucket: 'shopify-1ac61.firebasestorage.app',
    iosBundleId: 'com.example.shopify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqAr8hM4PmOxqvquj3KRhlomQeqUwrx7A',
    appId: '1:428336244677:ios:42fadee00e7855f107cdac',
    messagingSenderId: '428336244677',
    projectId: 'shopify-1ac61',
    storageBucket: 'shopify-1ac61.firebasestorage.app',
    iosBundleId: 'com.example.shopify',
  );
}
